language: node_js
node_js:
- node
cache: npm
script:
- npm run build
- npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: On3ei1VsDPATaY9vAm+7pPzz+N7tbmomvf11WDW4MbRMu87189ho5vLDfzzbkeXicT+GwMSjujsLVuJQ9d/Ev8gajtcuXHhrI30ICiGjmEL2f/7zSYXEP+xcdDWo1CZqCyQH/ZC+oR0aJRHFhs5A2qYp+uzX49pmrifxdTDCrYkTdaAdifF1erAE/P5wpb1Xn/XEPK5UrsVUjcqAnEgefMPXyBWieFinM1U9yzR1dLNS8XJOy/AAVAEzmtN3XFxQMMKl3GWATuhQ6s409VVNx/UEPjyezjlwWFaXIkQrXctRPSLbGD672WE/Rp8Oi2vj4GXygf0ldHA3Zok2roxgsxS88rmNH+GAJskGyaqlnPMR711/fQ0K40YB1oETtnkeTKpFtiOcJTMHa84/U379iV0i8xmPITAtAFowzpNKSzn36fGwS809vnPChnuikMnhyyHOBRK28pjkGBlTdsbRLOlqKU8bexeG7BIKZOFgsr62hb13XXZ8D4hcH/xB0yc9fNQaKq2ZjtUXxopYNPJ4bClsyOElzbPRPWc14XkPjjlQxUpcd6ciAshskCgjah3UUDZ2YLvxnLcmuR6uN0v/8r87bbgZ03fmpGMwxx/k1qFKDc3lHmmTwegrXblzvlgTuOokUv0aoIl6E4L9EEMSYG5FLsypa3S1KRMSP885iTM=
  app: open-trivia
  on:
    repo: olucasgomes/open-trivia
