language: node_js
node_js:
- node
cache: npm
script:
- npm run build
- npm run test:unit
deploy:
  provider: heroku
  api_key:
    secure: KrGoRyV34sKe8Rd1edqVLCSCpH8kAOAA52qDhEaiiqJu8vjRiQ+1mc643e+jpzwWpO2oB1+lxDRTgkaxNWOhHtGytVhcJuPZ9TdGpkGk/R1raIfYjTHOJf7fWz8zGtBOXBXRBPSpWC2nz6FTPgVvSohzP30cxAlxVPJnzigJJS/sJTrNeqR1uCSMVBCrCzVLr+qpCt6MnG90ljQOoO9n78W9bD9ysN5JCwOrlrtPIBdXzJAZXc8MsT4RgvMD2SC217+uIuCXNCevnBLadubhKfxbb2koM5HVNJ53mSDNvPIBoFoe1/Do901M09H4z8JKrdokJ2zs1fiCHpG3i0Y98owyAjofCpFWaethjt/TAx3ClGvv5qYHb/sU+gveX68nOR75nCsjyas1zqeGwXCwI4z+7a4y1qQAPEqV9LZM9heNK1a76OgfM1ywziegTpGw4ZjcdLLHcynVT2uJchLNLbkG1aXeko3TXq+ORk9j7qVs/35DXBC6Gk/XLqOzzeEkXm1rJNJk/NgZ+aIoEPHugzQIJm/07WG1BDsNO1MBl93521iysmq44BRQbbD4AVgAvSyOQarbjGa4LjywmHiWNsCk6CPy0E9KHozY6w9FmA3iaNV9Zf5iPqingMSM04q0PpPL45AQdB3o/Sf41QQC5uqTC6dtCAjQnVG9K5jDC2U=
  app: open-trivia
  on:
    repo: olucasgomes/open-trivia
